### ISSUE TITLE
Invoicing app for DAOs

### ISSUE THREAD

**Issue by arminvoid** [Blockternship/projects#11]
Hi all, I am Arpit. I have had 3 years of working experience developing enterprise APIs (think Web2). As part of the [hacktoberfest'17](https://hacktoberfest.digitalocean.com/) I contributed to the InterPlanetary File System ([IPFS](http://ipfs.io/)) - The distributed web. That got me really interested in the world of decentralization (Web3). I am now reading about all things blockchain since the last one month. Two specific areas where I feel specifically intrigued are DAOs and B2B payments on the blockchain.

## Overview
The invoicing app will enable DAOs to request payments (and eventually manage subscriptions) from their clients. All the transaction assets (invoices, terms agreement etc) will be hosted on IPFS. This app will be built on [Request Network](https://request.network/#/) and tie up nicely with DAOs built on the AragonOS.

Imagine a DAO creates a payment request/subscription for a client. The client (who is monitoring the network for request payments) fulfills the payment and the invoicing app gets notified - based on which the DAO can perform actions on their side.
This app will stand on the shoulder of giants to leverage all the benefits that these giants (aragon and request network) provide.

* Aragon
  * Leverage the Aragon system of ACLs to request payments.
  * App upgradeability through voting mechanisms
* Request Network
  * The DAO can plugin the extensions (to the invoicing app) that are relevant to the jurisdiction in which the DAO is operating in. e.g. enabling governments to levy taxes on a business transaction.
  * Plug-in third party applications built on top of request network. For instance audit, accounting and credit scoring apps that query the DAO invoices and payments to generate reports and take actions.

This project aims to create a highly modular DApp enabling the DAOs to plug in extensions and apps that fit their needs or facilitate them to fulfil their compliance obligations (e.g. pay taxes). Think of it like stripe but decentralised and highly flexible.

## Philosophy
Imagine businesses have started moving to the blockchain. Businesses owners are transacting locally and seamlessly across the geographical borders alike. They are paying taxes in real-time. The invoices being generated are recognized by the government. The statements are immutable, hence legitimate and reside on the decentralized internet. Companies don’t need need to worry about unintentional compliance violations. They can do away with the headache of filing taxes every month (like GST in India)

Multinational corporations no longer need to pay exorbitant fees to audit firms to audit their accounts. Companies no longer need to send invoices by email everyday and don’t have to worry about lost receipts at the end of the year. Accounting and audits will become a simple algorithmic check. The government is receiving taxes by the transaction. With this new found power of transparency, government revenue increases because tax evasion frauds have been eliminated. This leads the tax authorities to cut tax rates. Corporates and individuals can track that the taxes they paid went to government grants for cancer research.

Published as a twitter thread [here](https://twitter.com/atvanguard/status/1023885373707960320).

## Next Steps
I think this project is a great fit for @aragon. Ideally, I would like to see this app sit beside the other Aragon home grown [apps](https://wiki.aragon.org/dev/apps/). Some of the terms used above make more sense in the context of the request network [whitepaper](https://request.network/assets/pdf/request_whitepaper.pdf). I'd be happy to provide any more details.

### Contact Info
[Github](https://github.com/atvanguard), [Twitter](https://twitter.com/atvanguard), [Medium](https://medium.com/@atvanguard)

**Comment by YalorMewn** [comment]
Hey @atvanguard thx for submitting, are you looking for team mates on this as well ?

**Comment by arminvoid** [comment]
Yes, I am looking for a designer/UI person. But the work won't be very intensive because I would like to use the aragon UI components.

**Comment by YalorMewn** [comment]
Okay, make sure to reach out in the [Aragon chat](https://aragon.chat/home) to see if there is anyone in there interested in joining you. Also the [Giveth Social Coding](https://riot.im/app/#/group/+giveth:matrix.org) could be a good place to look for ppl. Just join the channel and say hello 👋🏼

**Comment by YalorMewn** [comment]
Hey @atvanguard I would like to invite you to the first call of the hackathon, would you send me a quick email here YalorTackson@gmail.com also you can add yourself to the event [here](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjlxM2dtdDd2bHA5ODNxbzNsYm5vOTMyZDkgeWFsb3J0YWNrc29uQG0&tmsrc=yalortackson%40gmail.com)

**Comment by izqui** [comment]
Hey @atvanguard! Awesome idea, it would be great for this app to trigger an incoming payment in Aragon's Finance app when the invoice is paid. This way the funds will securely be transferred to the DAO's Vault and the payment will be visible in the Finance UI of the DAO.

Reference: https://github.com/aragon/aragon-apps/blob/master/apps/finance/contracts/Finance.sol

**Comment by deamme** [comment]
@atvanguard Great project! It has now been approved. The project repository needs to be in this organization. We can create this for you. Any specific naming you want for the repo?

**Comment by arminvoid** [comment]
@izqui Thanks for the suggestion. Will keep in touch to exchange thoughts.
@deamme Thanks for approving. We can call it `smart-invoicing`.

**Comment by deamme** [comment]
@atvanguard Here it is https://github.com/Blockternship/smart-invoicing. You got admin access.

**Comment by YalorMewn** [comment]
Hey team your mentor will be @izqui with @Blockternship/team-aragon and the best place to reach them is https://aragon.chat/ look for @Jorge !

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: DAI: 630.00
Contract address: [0x522dfbf90f81a0eb01145b90262d9bbc7230350d](https://etherscan.io/address/0x522dfbf90f81a0eb01145b90262d9bbc7230350d)
Network: Mainnet
Paid to: atvanguard
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by YalorMewn** [comment]
Hey @atvanguard there is a bounty for you if you provide an update [here](https://riot.im/app/#/room/#blockternship:matrix.org) and ping @izqui

**Comment by YalorMewn** [comment]
Thanks for participating, don't forget to collect you bounty !
