### ISSUE TITLE
Savvy Crypto economics 

### ISSUE THREAD

**Issue by YalorMewn** [Blockternship/projects#2]
# Example of #Blockternship Issue Submission 

Hi all, I'm Yalor Mewn. I am brand new to development, big fan off all the projects involved with this hackathon but just starting how to learn code 😬

I work communications for a few blockchain projects, but I want to get more into development so here is my idea to get started: 

## Overview 
Savvy Crypto economics is a smart contract tool that allows you to automatically allocate any % of incoming crypto payments from any address to a third obfuscated address, we'll call it a savings account of sorts. 

## Philosophy 
The idea behind this project is to develop a tool that helps people save money, it's hard to save especially when you are a freelancer working with multiple projects and you don't always have time to create a solid budget for yourself. 

## Next Steps 
I think this project would be a great fit for @giveth because I hope to give this tool away for free to help people make better use of smart contracts with their finances. 

**Contact Info** 

GitHub: @YalorMewn 
Keybase: @YalorMewn 
Ethereum Address: 0x12678499602abf5b694065D29Dce0d8962ed263d

**Comment by YalorMewn** [comment]
Here's how the function could work. 
<img width="587" alt="screen shot 2018-07-13 at 5 07 26 pm" src="https://user-images.githubusercontent.com/34845103/42698799-3e12e72e-86bf-11e8-8c97-e4c4ddacf70f.png">

**Comment by geleeroyale** [comment]
Great idea! Maybe you get Alon to help you - as you might have seen, the multisend contract could be a nice start:

https://github.com/Alonski/MultiSendEthereum

**Comment by Quazia** [comment]
Hmm, obfuscation is hard. Otherwise sounds cool! Any plans for a UI?

**Comment by YalorMewn** [comment]
Thanks for the recommendation @geleeroyale I'll reach out to him and see what I can learn, And @Quazia I' guessing a UI would be required to be considered a complete tool right ?
