### ISSUE TITLE
dPanc - Self Health Management dApp for Diabetes

### ISSUE THREAD

**Issue by aasimsayani** [Blockternship/projects#20]
Hi, we are Aasim, Jakob, and Kevin we are all Software Developers and we have all recently started developing on the blockchain. We are three developers with experience developing on Colony.js, Solidity, etc...

**Overview** 

We wanted to tackle the initial challenge of being able to put medical data on the blockchain, and specifically data regarding type one diabetes. We are looking to give the average diabetic tools to better manage their health using a decentralized platform that stood objectively for their health, rather than the interests of the healthcare industry.

The existing medical prescription leaves a lot to be desired. Endocrinologists simply give their diabetic patients a linear equation that was interpolated from the patient’s recent medical data. But this linear equation ignores the fact that modern humans live very dynamic lives, and thus many diabetics self-prescribe their own tools and methods for dealing with the non-linear nature of the human experience.

We can bring engineers, diabetics, and health experts together to create an open sourced and decentralized diabetes management system. Through the analysis of medical data stored on an immutable ledger, we can provide the data to build these tools and iterate on them. We are confident that we can create dynamic models that can easily outperform the existing linear prescription, thus giving diabetics around the world more control over their health.

We would also like to explore an abstraction of this idea. The notion of individual people voluntarily providing their own data in order to help create a decentralized solution to a major world problem.

**Philosophy** 

We believe that the burden of type one diabetes can be significantly reduced if patients were given the appropriate tools to manage their health. But the tools being prescribed by doctors are inadequate, and the centralization of these tools make changes slow and ineffective. If individual patients shared their medical data to support the creation of these decentralized tools, we can bring the ability to enact change to the people whom it will affect the most.

**Next Steps** 

Our next steps are to build a dApp based on the Ethereum blockchain that would allow us to take data from our colleagues' current medical device to build a test case for our project. Following this we would be looking to grow our data and see the types of analysis we can provide. We will gather data through a front-end mobile/web application and utilize components such as the smart contracts to deal with the data.

**GitHub**- @aasimsayani, @jakobsandberg, @KevinLiLu

**Comment by YalorMewn** [comment]
Happy to see you here, looks like you just made the deadline ! 
This idea is especially close to my heart 💉❣️  due to the fact that my collage roommate struggled with diabetes. I look forward to reviewing but please allow a few days for us to respond to your submission.

**Comment by YalorMewn** [comment]
You're project has been approved ! 
Would you like us to fork a repo in for you or start a fresh one ?

**Comment by aasimsayani** [comment]
We would like to start a fresh one if that works for you guys! Thank you! @YalorMewn

**Comment by YalorMewn** [comment]
Here you go https://github.com/Blockternship/dPanc you have full admin access, also @gichiba from #Colony is you're mentor you can connect with him on [Riot](file:///Applications/Riot.app/Contents/Resources/webapp/index.html#/room/#blockternship:matrix.org)

**Comment by YalorMewn** [comment]
Here you go: https://github.com/Blockternship/dPanc you have full access and you're mentor is @gichiba from Colony you can connect with him on Riot here:  https://riot.im/app/#/room/#blockternship:matrix.org

**Comment by ryanchristo** [comment]
Hey @jakobsandberg, @aasimsayani and @KevinLiLu! Nice to see a couple familiar faces. Great work on colonyExplorer. Looking forward to seeing this project take shape. I'll be helping out @gichiba with support. Let us know if you have any initial questions. We'll be in touch.

**Comment by status-open-bounty** [comment]
Balance: 0.5 ETH
Contract address: [0xd1358d9560ffe120df32369a4d7eca65d6f5df7c](https://etherscan.io/address/0xd1358d9560ffe120df32369a4d7eca65d6f5df7c)
Network: Mainnet
Status: Pending maintainer confirmation
Winner: aasimsayani
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by KevinLiLu** [comment]
@YalorMewn @geleeroyale 

Can you guys give us write access to our Blockternship repo (https://github.com/Blockternship/dPanc)? We've been working in a personal repo for now, but we should switch over. 

@aasimsayani @KevinLiLu @jakobsandberg

Thanks!

**Comment by ryanchristo** [comment]
@KevinLiLu Just added you as an admin for the repository.

<img width="729" alt="screen shot 2018-08-24 at 11 46 25 am" src="https://user-images.githubusercontent.com/12519942/44565655-78971b00-a793-11e8-89fb-1ad2c89f1be6.png">

**Comment by KevinLiLu** [comment]
@ryanchristo Thanks! 😄

**Comment by liamzebedee** [comment]
Yo, I've had T1 Diabetes for 10 years and do blockchain/fullstack dev ❤️This seems like a great initiative.

Have you lot heard about [Tidepool](http://tidepool.org/). They are completely open-source AFAIK, and their uploader tool works for many varieties of insulin pumps and BG meters, with regular improvements. I'm not so sure about your colleague's situation though!

**Comment by YalorMewn** [comment]
Hey @liamzebedee you should join https://riot.im/app/#/room/#blockternship:matrix.org if you want to connect with the team working on this :)

**Comment by KevinLiLu** [comment]
@liamzebedee I have not heard of Tidepool before, but I will definitely take a look! Thanks for the suggestion!

**Comment by YalorMewn** [comment]
Thanks for participating, don't forget to collect you bounty !

**Comment by geleeroyale** [comment]
Please don't close issues until bounty is paid out!!
